if (Meteor.isClient) {
  // counter starts at 0
  Session.setDefault('counter', 0);

  Template.mixitupInstance.helpers({
    times10: function (myfloat) {
      return(myfloat*10)
    }
  })
  Template.mixitup.helpers({
    figures: function() {
      return [
{alpha: 0.5, muscleNum: 1, bound: 'upperbound', shortname: 'adf', fullname: 'Adductor femoris'},
{alpha: 0.6, muscleNum: 1, bound: 'upperbound', shortname: 'adf', fullname: 'Adductor femoris'},
{alpha: 0.7, muscleNum: 1, bound: 'upperbound', shortname: 'adf', fullname: 'Adductor femoris'},
{alpha: 0.8, muscleNum: 1, bound: 'upperbound', shortname: 'adf', fullname: 'Adductor femoris'},
{alpha: 0.9, muscleNum: 1, bound: 'upperbound', shortname: 'adf', fullname: 'Adductor femoris'},
{alpha: 0.5, muscleNum: 2, bound: 'upperbound', shortname: 'adl', fullname: 'Adductor longus'},
{alpha: 0.6, muscleNum: 2, bound: 'upperbound', shortname: 'adl', fullname: 'Adductor longus'},
{alpha: 0.7, muscleNum: 2, bound: 'upperbound', shortname: 'adl', fullname: 'Adductor longus'},
{alpha: 0.8, muscleNum: 2, bound: 'upperbound', shortname: 'adl', fullname: 'Adductor longus'},
{alpha: 0.9, muscleNum: 2, bound: 'upperbound', shortname: 'adl', fullname: 'Adductor longus'},
{alpha: 0.5, muscleNum: 3, bound: 'upperbound', shortname: 'bfa', fullname: 'Biceps femoris anterior'},
{alpha: 0.6, muscleNum: 3, bound: 'upperbound', shortname: 'bfa', fullname: 'Biceps femoris anterior'},
{alpha: 0.7, muscleNum: 3, bound: 'upperbound', shortname: 'bfa', fullname: 'Biceps femoris anterior'},
{alpha: 0.8, muscleNum: 3, bound: 'upperbound', shortname: 'bfa', fullname: 'Biceps femoris anterior'},
{alpha: 0.9, muscleNum: 3, bound: 'upperbound', shortname: 'bfa', fullname: 'Biceps femoris anterior'},
{alpha: 0.5, muscleNum: 4, bound: 'upperbound', shortname: 'bfp', fullname: 'Biceps femoris posterior'},
{alpha: 0.6, muscleNum: 4, bound: 'upperbound', shortname: 'bfp', fullname: 'Biceps femoris posterior'},
{alpha: 0.7, muscleNum: 4, bound: 'upperbound', shortname: 'bfp', fullname: 'Biceps femoris posterior'},
{alpha: 0.8, muscleNum: 4, bound: 'upperbound', shortname: 'bfp', fullname: 'Biceps femoris posterior'},
{alpha: 0.9, muscleNum: 4, bound: 'upperbound', shortname: 'bfp', fullname: 'Biceps femoris posterior'},
{alpha: 0.5, muscleNum: 5, bound: 'upperbound', shortname: 'edl', fullname: 'Extensor digitorum longus'},
{alpha: 0.6, muscleNum: 5, bound: 'upperbound', shortname: 'edl', fullname: 'Extensor digitorum longus'},
{alpha: 0.7, muscleNum: 5, bound: 'upperbound', shortname: 'edl', fullname: 'Extensor digitorum longus'},
{alpha: 0.8, muscleNum: 5, bound: 'upperbound', shortname: 'edl', fullname: 'Extensor digitorum longus'},
{alpha: 0.9, muscleNum: 5, bound: 'upperbound', shortname: 'edl', fullname: 'Extensor digitorum longus'},
{alpha: 0.5, muscleNum: 6, bound: 'upperbound', shortname: 'fdl', fullname: 'Flexor digitorum longus'},
{alpha: 0.6, muscleNum: 6, bound: 'upperbound', shortname: 'fdl', fullname: 'Flexor digitorum longus'},
{alpha: 0.7, muscleNum: 6, bound: 'upperbound', shortname: 'fdl', fullname: 'Flexor digitorum longus'},
{alpha: 0.8, muscleNum: 6, bound: 'upperbound', shortname: 'fdl', fullname: 'Flexor digitorum longus'},
{alpha: 0.9, muscleNum: 6, bound: 'upperbound', shortname: 'fdl', fullname: 'Flexor digitorum longus'},
{alpha: 0.5, muscleNum: 7, bound: 'upperbound', shortname: 'fhl', fullname: 'Flexor hallicus longus'},
{alpha: 0.6, muscleNum: 7, bound: 'upperbound', shortname: 'fhl', fullname: 'Flexor hallicus longus'},
{alpha: 0.7, muscleNum: 7, bound: 'upperbound', shortname: 'fhl', fullname: 'Flexor hallicus longus'},
{alpha: 0.8, muscleNum: 7, bound: 'upperbound', shortname: 'fhl', fullname: 'Flexor hallicus longus'},
{alpha: 0.9, muscleNum: 7, bound: 'upperbound', shortname: 'fhl', fullname: 'Flexor hallicus longus'},
{alpha: 0.5, muscleNum: 8, bound: 'upperbound', shortname: 'gmax', fullname: 'Gluteus maximus'},
{alpha: 0.6, muscleNum: 8, bound: 'upperbound', shortname: 'gmax', fullname: 'Gluteus maximus'},
{alpha: 0.7, muscleNum: 8, bound: 'upperbound', shortname: 'gmax', fullname: 'Gluteus maximus'},
{alpha: 0.8, muscleNum: 8, bound: 'upperbound', shortname: 'gmax', fullname: 'Gluteus maximus'},
{alpha: 0.9, muscleNum: 8, bound: 'upperbound', shortname: 'gmax', fullname: 'Gluteus maximus'},
{alpha: 0.5, muscleNum: 9, bound: 'upperbound', shortname: 'gmed', fullname: 'Gluteus medius'},
{alpha: 0.6, muscleNum: 9, bound: 'upperbound', shortname: 'gmed', fullname: 'Gluteus medius'},
{alpha: 0.7, muscleNum: 9, bound: 'upperbound', shortname: 'gmed', fullname: 'Gluteus medius'},
{alpha: 0.8, muscleNum: 9, bound: 'upperbound', shortname: 'gmed', fullname: 'Gluteus medius'},
{alpha: 0.9, muscleNum: 9, bound: 'upperbound', shortname: 'gmed', fullname: 'Gluteus medius'},
{alpha: 0.5, muscleNum: 10, bound: 'upperbound', shortname: 'gmin', fullname: 'Gluteus minimus'},
{alpha: 0.6, muscleNum: 10, bound: 'upperbound', shortname: 'gmin', fullname: 'Gluteus minimus'},
{alpha: 0.7, muscleNum: 10, bound: 'upperbound', shortname: 'gmin', fullname: 'Gluteus minimus'},
{alpha: 0.8, muscleNum: 10, bound: 'upperbound', shortname: 'gmin', fullname: 'Gluteus minimus'},
{alpha: 0.9, muscleNum: 10, bound: 'upperbound', shortname: 'gmin', fullname: 'Gluteus minimus'},
{alpha: 0.5, muscleNum: 11, bound: 'upperbound', shortname: 'grac', fullname: 'Gracilis'},
{alpha: 0.6, muscleNum: 11, bound: 'upperbound', shortname: 'grac', fullname: 'Gracilis'},
{alpha: 0.7, muscleNum: 11, bound: 'upperbound', shortname: 'grac', fullname: 'Gracilis'},
{alpha: 0.8, muscleNum: 11, bound: 'upperbound', shortname: 'grac', fullname: 'Gracilis'},
{alpha: 0.9, muscleNum: 11, bound: 'upperbound', shortname: 'grac', fullname: 'Gracilis'},
{alpha: 0.5, muscleNum: 12, bound: 'upperbound', shortname: 'lg', fullname: 'Lateral gastrocnemius'},
{alpha: 0.6, muscleNum: 12, bound: 'upperbound', shortname: 'lg', fullname: 'Lateral gastrocnemius'},
{alpha: 0.7, muscleNum: 12, bound: 'upperbound', shortname: 'lg', fullname: 'Lateral gastrocnemius'},
{alpha: 0.8, muscleNum: 12, bound: 'upperbound', shortname: 'lg', fullname: 'Lateral gastrocnemius'},
{alpha: 0.9, muscleNum: 12, bound: 'upperbound', shortname: 'lg', fullname: 'Lateral gastrocnemius'},
{alpha: 0.5, muscleNum: 13, bound: 'upperbound', shortname: 'mg', fullname: 'Medial gastrocnemius'},
{alpha: 0.6, muscleNum: 13, bound: 'upperbound', shortname: 'mg', fullname: 'Medial gastrocnemius'},
{alpha: 0.7, muscleNum: 13, bound: 'upperbound', shortname: 'mg', fullname: 'Medial gastrocnemius'},
{alpha: 0.8, muscleNum: 13, bound: 'upperbound', shortname: 'mg', fullname: 'Medial gastrocnemius'},
{alpha: 0.9, muscleNum: 13, bound: 'upperbound', shortname: 'mg', fullname: 'Medial gastrocnemius'},
{alpha: 0.5, muscleNum: 14, bound: 'upperbound', shortname: 'pb', fullname: 'Peroneus brevis'},
{alpha: 0.6, muscleNum: 14, bound: 'upperbound', shortname: 'pb', fullname: 'Peroneus brevis'},
{alpha: 0.7, muscleNum: 14, bound: 'upperbound', shortname: 'pb', fullname: 'Peroneus brevis'},
{alpha: 0.8, muscleNum: 14, bound: 'upperbound', shortname: 'pb', fullname: 'Peroneus brevis'},
{alpha: 0.9, muscleNum: 14, bound: 'upperbound', shortname: 'pb', fullname: 'Peroneus brevis'},
{alpha: 0.5, muscleNum: 15, bound: 'upperbound', shortname: 'pec', fullname: 'Pectineus'},
{alpha: 0.6, muscleNum: 15, bound: 'upperbound', shortname: 'pec', fullname: 'Pectineus'},
{alpha: 0.7, muscleNum: 15, bound: 'upperbound', shortname: 'pec', fullname: 'Pectineus'},
{alpha: 0.8, muscleNum: 15, bound: 'upperbound', shortname: 'pec', fullname: 'Pectineus'},
{alpha: 0.9, muscleNum: 15, bound: 'upperbound', shortname: 'pec', fullname: 'Pectineus'},
{alpha: 0.5, muscleNum: 16, bound: 'upperbound', shortname: 'pl', fullname: 'Peroneus longus'},
{alpha: 0.6, muscleNum: 16, bound: 'upperbound', shortname: 'pl', fullname: 'Peroneus longus'},
{alpha: 0.7, muscleNum: 16, bound: 'upperbound', shortname: 'pl', fullname: 'Peroneus longus'},
{alpha: 0.8, muscleNum: 16, bound: 'upperbound', shortname: 'pl', fullname: 'Peroneus longus'},
{alpha: 0.9, muscleNum: 16, bound: 'upperbound', shortname: 'pl', fullname: 'Peroneus longus'},
{alpha: 0.5, muscleNum: 17, bound: 'upperbound', shortname: 'plan', fullname: 'Plantaris'},
{alpha: 0.6, muscleNum: 17, bound: 'upperbound', shortname: 'plan', fullname: 'Plantaris'},
{alpha: 0.7, muscleNum: 17, bound: 'upperbound', shortname: 'plan', fullname: 'Plantaris'},
{alpha: 0.8, muscleNum: 17, bound: 'upperbound', shortname: 'plan', fullname: 'Plantaris'},
{alpha: 0.9, muscleNum: 17, bound: 'upperbound', shortname: 'plan', fullname: 'Plantaris'},
{alpha: 0.5, muscleNum: 18, bound: 'upperbound', shortname: 'psoas', fullname: 'Iliopsoas'},
{alpha: 0.6, muscleNum: 18, bound: 'upperbound', shortname: 'psoas', fullname: 'Iliopsoas'},
{alpha: 0.7, muscleNum: 18, bound: 'upperbound', shortname: 'psoas', fullname: 'Iliopsoas'},
{alpha: 0.8, muscleNum: 18, bound: 'upperbound', shortname: 'psoas', fullname: 'Iliopsoas'},
{alpha: 0.9, muscleNum: 18, bound: 'upperbound', shortname: 'psoas', fullname: 'Iliopsoas'},
{alpha: 0.5, muscleNum: 19, bound: 'upperbound', shortname: 'pt', fullname: 'Peroneus tertius'},
{alpha: 0.6, muscleNum: 19, bound: 'upperbound', shortname: 'pt', fullname: 'Peroneus tertius'},
{alpha: 0.7, muscleNum: 19, bound: 'upperbound', shortname: 'pt', fullname: 'Peroneus tertius'},
{alpha: 0.8, muscleNum: 19, bound: 'upperbound', shortname: 'pt', fullname: 'Peroneus tertius'},
{alpha: 0.9, muscleNum: 19, bound: 'upperbound', shortname: 'pt', fullname: 'Peroneus tertius'},
{alpha: 0.5, muscleNum: 20, bound: 'upperbound', shortname: 'pyr', fullname: 'Pyriformis'},
{alpha: 0.6, muscleNum: 20, bound: 'upperbound', shortname: 'pyr', fullname: 'Pyriformis'},
{alpha: 0.7, muscleNum: 20, bound: 'upperbound', shortname: 'pyr', fullname: 'Pyriformis'},
{alpha: 0.8, muscleNum: 20, bound: 'upperbound', shortname: 'pyr', fullname: 'Pyriformis'},
{alpha: 0.9, muscleNum: 20, bound: 'upperbound', shortname: 'pyr', fullname: 'Pyriformis'},
{alpha: 0.5, muscleNum: 21, bound: 'upperbound', shortname: 'qf', fullname: 'Quadratus femoris'},
{alpha: 0.6, muscleNum: 21, bound: 'upperbound', shortname: 'qf', fullname: 'Quadratus femoris'},
{alpha: 0.7, muscleNum: 21, bound: 'upperbound', shortname: 'qf', fullname: 'Quadratus femoris'},
{alpha: 0.8, muscleNum: 21, bound: 'upperbound', shortname: 'qf', fullname: 'Quadratus femoris'},
{alpha: 0.9, muscleNum: 21, bound: 'upperbound', shortname: 'qf', fullname: 'Quadratus femoris'},
{alpha: 0.5, muscleNum: 22, bound: 'upperbound', shortname: 'rf', fullname: 'Rectus femoris'},
{alpha: 0.6, muscleNum: 22, bound: 'upperbound', shortname: 'rf', fullname: 'Rectus femoris'},
{alpha: 0.7, muscleNum: 22, bound: 'upperbound', shortname: 'rf', fullname: 'Rectus femoris'},
{alpha: 0.8, muscleNum: 22, bound: 'upperbound', shortname: 'rf', fullname: 'Rectus femoris'},
{alpha: 0.9, muscleNum: 22, bound: 'upperbound', shortname: 'rf', fullname: 'Rectus femoris'},
{alpha: 0.5, muscleNum: 23, bound: 'upperbound', shortname: 'sart', fullname: 'Sartorius'},
{alpha: 0.6, muscleNum: 23, bound: 'upperbound', shortname: 'sart', fullname: 'Sartorius'},
{alpha: 0.7, muscleNum: 23, bound: 'upperbound', shortname: 'sart', fullname: 'Sartorius'},
{alpha: 0.8, muscleNum: 23, bound: 'upperbound', shortname: 'sart', fullname: 'Sartorius'},
{alpha: 0.9, muscleNum: 23, bound: 'upperbound', shortname: 'sart', fullname: 'Sartorius'},
{alpha: 0.5, muscleNum: 24, bound: 'upperbound', shortname: 'sm', fullname: 'Semimembranossus'},
{alpha: 0.6, muscleNum: 24, bound: 'upperbound', shortname: 'sm', fullname: 'Semimembranossus'},
{alpha: 0.7, muscleNum: 24, bound: 'upperbound', shortname: 'sm', fullname: 'Semimembranossus'},
{alpha: 0.8, muscleNum: 24, bound: 'upperbound', shortname: 'sm', fullname: 'Semimembranossus'},
{alpha: 0.9, muscleNum: 24, bound: 'upperbound', shortname: 'sm', fullname: 'Semimembranossus'},
{alpha: 0.5, muscleNum: 25, bound: 'upperbound', shortname: 'sol', fullname: 'Soleus'},
{alpha: 0.6, muscleNum: 25, bound: 'upperbound', shortname: 'sol', fullname: 'Soleus'},
{alpha: 0.7, muscleNum: 25, bound: 'upperbound', shortname: 'sol', fullname: 'Soleus'},
{alpha: 0.8, muscleNum: 25, bound: 'upperbound', shortname: 'sol', fullname: 'Soleus'},
{alpha: 0.9, muscleNum: 25, bound: 'upperbound', shortname: 'sol', fullname: 'Soleus'},
{alpha: 0.5, muscleNum: 26, bound: 'upperbound', shortname: 'st', fullname: 'Semitendinosus'},
{alpha: 0.6, muscleNum: 26, bound: 'upperbound', shortname: 'st', fullname: 'Semitendinosus'},
{alpha: 0.7, muscleNum: 26, bound: 'upperbound', shortname: 'st', fullname: 'Semitendinosus'},
{alpha: 0.8, muscleNum: 26, bound: 'upperbound', shortname: 'st', fullname: 'Semitendinosus'},
{alpha: 0.9, muscleNum: 26, bound: 'upperbound', shortname: 'st', fullname: 'Semitendinosus'},
{alpha: 0.5, muscleNum: 27, bound: 'upperbound', shortname: 'ta', fullname: 'Tibialis anterior'},
{alpha: 0.6, muscleNum: 27, bound: 'upperbound', shortname: 'ta', fullname: 'Tibialis anterior'},
{alpha: 0.7, muscleNum: 27, bound: 'upperbound', shortname: 'ta', fullname: 'Tibialis anterior'},
{alpha: 0.8, muscleNum: 27, bound: 'upperbound', shortname: 'ta', fullname: 'Tibialis anterior'},
{alpha: 0.9, muscleNum: 27, bound: 'upperbound', shortname: 'ta', fullname: 'Tibialis anterior'},
{alpha: 0.5, muscleNum: 28, bound: 'upperbound', shortname: 'tp', fullname: 'Tibialis posterior'},
{alpha: 0.6, muscleNum: 28, bound: 'upperbound', shortname: 'tp', fullname: 'Tibialis posterior'},
{alpha: 0.7, muscleNum: 28, bound: 'upperbound', shortname: 'tp', fullname: 'Tibialis posterior'},
{alpha: 0.8, muscleNum: 28, bound: 'upperbound', shortname: 'tp', fullname: 'Tibialis posterior'},
{alpha: 0.9, muscleNum: 28, bound: 'upperbound', shortname: 'tp', fullname: 'Tibialis posterior'},
{alpha: 0.5, muscleNum: 29, bound: 'upperbound', shortname: 'vi', fullname: 'Vastus intermedius'},
{alpha: 0.6, muscleNum: 29, bound: 'upperbound', shortname: 'vi', fullname: 'Vastus intermedius'},
{alpha: 0.7, muscleNum: 29, bound: 'upperbound', shortname: 'vi', fullname: 'Vastus intermedius'},
{alpha: 0.8, muscleNum: 29, bound: 'upperbound', shortname: 'vi', fullname: 'Vastus intermedius'},
{alpha: 0.9, muscleNum: 29, bound: 'upperbound', shortname: 'vi', fullname: 'Vastus intermedius'},
{alpha: 0.5, muscleNum: 30, bound: 'upperbound', shortname: 'vl', fullname: 'Vastus lateralis'},
{alpha: 0.6, muscleNum: 30, bound: 'upperbound', shortname: 'vl', fullname: 'Vastus lateralis'},
{alpha: 0.7, muscleNum: 30, bound: 'upperbound', shortname: 'vl', fullname: 'Vastus lateralis'},
{alpha: 0.8, muscleNum: 30, bound: 'upperbound', shortname: 'vl', fullname: 'Vastus lateralis'},
{alpha: 0.9, muscleNum: 30, bound: 'upperbound', shortname: 'vl', fullname: 'Vastus lateralis'},
{alpha: 0.5, muscleNum: 31, bound: 'upperbound', shortname: 'vm', fullname: 'Vastus medialis'},
{alpha: 0.6, muscleNum: 31, bound: 'upperbound', shortname: 'vm', fullname: 'Vastus medialis'},
{alpha: 0.7, muscleNum: 31, bound: 'upperbound', shortname: 'vm', fullname: 'Vastus medialis'},
{alpha: 0.8, muscleNum: 31, bound: 'upperbound', shortname: 'vm', fullname: 'Vastus medialis'},
{alpha: 0.9, muscleNum: 31, bound: 'upperbound', shortname: 'vm', fullname: 'Vastus medialis'},
{alpha: 0.5, muscleNum: 1, bound: 'lowerbound', shortname: 'adf', fullname: 'Adductor femoris'},
{alpha: 0.6, muscleNum: 1, bound: 'lowerbound', shortname: 'adf', fullname: 'Adductor femoris'},
{alpha: 0.7, muscleNum: 1, bound: 'lowerbound', shortname: 'adf', fullname: 'Adductor femoris'},
{alpha: 0.8, muscleNum: 1, bound: 'lowerbound', shortname: 'adf', fullname: 'Adductor femoris'},
{alpha: 0.9, muscleNum: 1, bound: 'lowerbound', shortname: 'adf', fullname: 'Adductor femoris'},
{alpha: 0.5, muscleNum: 2, bound: 'lowerbound', shortname: 'adl', fullname: 'Adductor longus'},
{alpha: 0.6, muscleNum: 2, bound: 'lowerbound', shortname: 'adl', fullname: 'Adductor longus'},
{alpha: 0.7, muscleNum: 2, bound: 'lowerbound', shortname: 'adl', fullname: 'Adductor longus'},
{alpha: 0.8, muscleNum: 2, bound: 'lowerbound', shortname: 'adl', fullname: 'Adductor longus'},
{alpha: 0.9, muscleNum: 2, bound: 'lowerbound', shortname: 'adl', fullname: 'Adductor longus'},
{alpha: 0.5, muscleNum: 3, bound: 'lowerbound', shortname: 'bfa', fullname: 'Biceps femoris anterior'},
{alpha: 0.6, muscleNum: 3, bound: 'lowerbound', shortname: 'bfa', fullname: 'Biceps femoris anterior'},
{alpha: 0.7, muscleNum: 3, bound: 'lowerbound', shortname: 'bfa', fullname: 'Biceps femoris anterior'},
{alpha: 0.8, muscleNum: 3, bound: 'lowerbound', shortname: 'bfa', fullname: 'Biceps femoris anterior'},
{alpha: 0.9, muscleNum: 3, bound: 'lowerbound', shortname: 'bfa', fullname: 'Biceps femoris anterior'},
{alpha: 0.5, muscleNum: 4, bound: 'lowerbound', shortname: 'bfp', fullname: 'Biceps femoris posterior'},
{alpha: 0.6, muscleNum: 4, bound: 'lowerbound', shortname: 'bfp', fullname: 'Biceps femoris posterior'},
{alpha: 0.7, muscleNum: 4, bound: 'lowerbound', shortname: 'bfp', fullname: 'Biceps femoris posterior'},
{alpha: 0.8, muscleNum: 4, bound: 'lowerbound', shortname: 'bfp', fullname: 'Biceps femoris posterior'},
{alpha: 0.9, muscleNum: 4, bound: 'lowerbound', shortname: 'bfp', fullname: 'Biceps femoris posterior'},
{alpha: 0.5, muscleNum: 5, bound: 'lowerbound', shortname: 'edl', fullname: 'Extensor digitorum longus'},
{alpha: 0.6, muscleNum: 5, bound: 'lowerbound', shortname: 'edl', fullname: 'Extensor digitorum longus'},
{alpha: 0.7, muscleNum: 5, bound: 'lowerbound', shortname: 'edl', fullname: 'Extensor digitorum longus'},
{alpha: 0.8, muscleNum: 5, bound: 'lowerbound', shortname: 'edl', fullname: 'Extensor digitorum longus'},
{alpha: 0.9, muscleNum: 5, bound: 'lowerbound', shortname: 'edl', fullname: 'Extensor digitorum longus'},
{alpha: 0.5, muscleNum: 6, bound: 'lowerbound', shortname: 'fdl', fullname: 'Flexor digitorum longus'},
{alpha: 0.6, muscleNum: 6, bound: 'lowerbound', shortname: 'fdl', fullname: 'Flexor digitorum longus'},
{alpha: 0.7, muscleNum: 6, bound: 'lowerbound', shortname: 'fdl', fullname: 'Flexor digitorum longus'},
{alpha: 0.8, muscleNum: 6, bound: 'lowerbound', shortname: 'fdl', fullname: 'Flexor digitorum longus'},
{alpha: 0.9, muscleNum: 6, bound: 'lowerbound', shortname: 'fdl', fullname: 'Flexor digitorum longus'},
{alpha: 0.5, muscleNum: 7, bound: 'lowerbound', shortname: 'fhl', fullname: 'Flexor hallicus longus'},
{alpha: 0.6, muscleNum: 7, bound: 'lowerbound', shortname: 'fhl', fullname: 'Flexor hallicus longus'},
{alpha: 0.7, muscleNum: 7, bound: 'lowerbound', shortname: 'fhl', fullname: 'Flexor hallicus longus'},
{alpha: 0.8, muscleNum: 7, bound: 'lowerbound', shortname: 'fhl', fullname: 'Flexor hallicus longus'},
{alpha: 0.9, muscleNum: 7, bound: 'lowerbound', shortname: 'fhl', fullname: 'Flexor hallicus longus'},
{alpha: 0.5, muscleNum: 8, bound: 'lowerbound', shortname: 'gmax', fullname: 'Gluteus maximus'},
{alpha: 0.6, muscleNum: 8, bound: 'lowerbound', shortname: 'gmax', fullname: 'Gluteus maximus'},
{alpha: 0.7, muscleNum: 8, bound: 'lowerbound', shortname: 'gmax', fullname: 'Gluteus maximus'},
{alpha: 0.8, muscleNum: 8, bound: 'lowerbound', shortname: 'gmax', fullname: 'Gluteus maximus'},
{alpha: 0.9, muscleNum: 8, bound: 'lowerbound', shortname: 'gmax', fullname: 'Gluteus maximus'},
{alpha: 0.5, muscleNum: 9, bound: 'lowerbound', shortname: 'gmed', fullname: 'Gluteus medius'},
{alpha: 0.6, muscleNum: 9, bound: 'lowerbound', shortname: 'gmed', fullname: 'Gluteus medius'},
{alpha: 0.7, muscleNum: 9, bound: 'lowerbound', shortname: 'gmed', fullname: 'Gluteus medius'},
{alpha: 0.8, muscleNum: 9, bound: 'lowerbound', shortname: 'gmed', fullname: 'Gluteus medius'},
{alpha: 0.9, muscleNum: 9, bound: 'lowerbound', shortname: 'gmed', fullname: 'Gluteus medius'},
{alpha: 0.5, muscleNum: 10, bound: 'lowerbound', shortname: 'gmin', fullname: 'Gluteus minimus'},
{alpha: 0.6, muscleNum: 10, bound: 'lowerbound', shortname: 'gmin', fullname: 'Gluteus minimus'},
{alpha: 0.7, muscleNum: 10, bound: 'lowerbound', shortname: 'gmin', fullname: 'Gluteus minimus'},
{alpha: 0.8, muscleNum: 10, bound: 'lowerbound', shortname: 'gmin', fullname: 'Gluteus minimus'},
{alpha: 0.9, muscleNum: 10, bound: 'lowerbound', shortname: 'gmin', fullname: 'Gluteus minimus'},
{alpha: 0.5, muscleNum: 11, bound: 'lowerbound', shortname: 'grac', fullname: 'Gracilis'},
{alpha: 0.6, muscleNum: 11, bound: 'lowerbound', shortname: 'grac', fullname: 'Gracilis'},
{alpha: 0.7, muscleNum: 11, bound: 'lowerbound', shortname: 'grac', fullname: 'Gracilis'},
{alpha: 0.8, muscleNum: 11, bound: 'lowerbound', shortname: 'grac', fullname: 'Gracilis'},
{alpha: 0.9, muscleNum: 11, bound: 'lowerbound', shortname: 'grac', fullname: 'Gracilis'},
{alpha: 0.5, muscleNum: 12, bound: 'lowerbound', shortname: 'lg', fullname: 'Lateral gastrocnemius'},
{alpha: 0.6, muscleNum: 12, bound: 'lowerbound', shortname: 'lg', fullname: 'Lateral gastrocnemius'},
{alpha: 0.7, muscleNum: 12, bound: 'lowerbound', shortname: 'lg', fullname: 'Lateral gastrocnemius'},
{alpha: 0.8, muscleNum: 12, bound: 'lowerbound', shortname: 'lg', fullname: 'Lateral gastrocnemius'},
{alpha: 0.9, muscleNum: 12, bound: 'lowerbound', shortname: 'lg', fullname: 'Lateral gastrocnemius'},
{alpha: 0.5, muscleNum: 13, bound: 'lowerbound', shortname: 'mg', fullname: 'Medial gastrocnemius'},
{alpha: 0.6, muscleNum: 13, bound: 'lowerbound', shortname: 'mg', fullname: 'Medial gastrocnemius'},
{alpha: 0.7, muscleNum: 13, bound: 'lowerbound', shortname: 'mg', fullname: 'Medial gastrocnemius'},
{alpha: 0.8, muscleNum: 13, bound: 'lowerbound', shortname: 'mg', fullname: 'Medial gastrocnemius'},
{alpha: 0.9, muscleNum: 13, bound: 'lowerbound', shortname: 'mg', fullname: 'Medial gastrocnemius'},
{alpha: 0.5, muscleNum: 14, bound: 'lowerbound', shortname: 'pb', fullname: 'Peroneus brevis'},
{alpha: 0.6, muscleNum: 14, bound: 'lowerbound', shortname: 'pb', fullname: 'Peroneus brevis'},
{alpha: 0.7, muscleNum: 14, bound: 'lowerbound', shortname: 'pb', fullname: 'Peroneus brevis'},
{alpha: 0.8, muscleNum: 14, bound: 'lowerbound', shortname: 'pb', fullname: 'Peroneus brevis'},
{alpha: 0.9, muscleNum: 14, bound: 'lowerbound', shortname: 'pb', fullname: 'Peroneus brevis'},
{alpha: 0.5, muscleNum: 15, bound: 'lowerbound', shortname: 'pec', fullname: 'Pectineus'},
{alpha: 0.6, muscleNum: 15, bound: 'lowerbound', shortname: 'pec', fullname: 'Pectineus'},
{alpha: 0.7, muscleNum: 15, bound: 'lowerbound', shortname: 'pec', fullname: 'Pectineus'},
{alpha: 0.8, muscleNum: 15, bound: 'lowerbound', shortname: 'pec', fullname: 'Pectineus'},
{alpha: 0.9, muscleNum: 15, bound: 'lowerbound', shortname: 'pec', fullname: 'Pectineus'},
{alpha: 0.5, muscleNum: 16, bound: 'lowerbound', shortname: 'pl', fullname: 'Peroneus longus'},
{alpha: 0.6, muscleNum: 16, bound: 'lowerbound', shortname: 'pl', fullname: 'Peroneus longus'},
{alpha: 0.7, muscleNum: 16, bound: 'lowerbound', shortname: 'pl', fullname: 'Peroneus longus'},
{alpha: 0.8, muscleNum: 16, bound: 'lowerbound', shortname: 'pl', fullname: 'Peroneus longus'},
{alpha: 0.9, muscleNum: 16, bound: 'lowerbound', shortname: 'pl', fullname: 'Peroneus longus'},
{alpha: 0.5, muscleNum: 17, bound: 'lowerbound', shortname: 'plan', fullname: 'Plantaris'},
{alpha: 0.6, muscleNum: 17, bound: 'lowerbound', shortname: 'plan', fullname: 'Plantaris'},
{alpha: 0.7, muscleNum: 17, bound: 'lowerbound', shortname: 'plan', fullname: 'Plantaris'},
{alpha: 0.8, muscleNum: 17, bound: 'lowerbound', shortname: 'plan', fullname: 'Plantaris'},
{alpha: 0.9, muscleNum: 17, bound: 'lowerbound', shortname: 'plan', fullname: 'Plantaris'},
{alpha: 0.5, muscleNum: 18, bound: 'lowerbound', shortname: 'psoas', fullname: 'Iliopsoas'},
{alpha: 0.6, muscleNum: 18, bound: 'lowerbound', shortname: 'psoas', fullname: 'Iliopsoas'},
{alpha: 0.7, muscleNum: 18, bound: 'lowerbound', shortname: 'psoas', fullname: 'Iliopsoas'},
{alpha: 0.8, muscleNum: 18, bound: 'lowerbound', shortname: 'psoas', fullname: 'Iliopsoas'},
{alpha: 0.9, muscleNum: 18, bound: 'lowerbound', shortname: 'psoas', fullname: 'Iliopsoas'},
{alpha: 0.5, muscleNum: 19, bound: 'lowerbound', shortname: 'pt', fullname: 'Peroneus tertius'},
{alpha: 0.6, muscleNum: 19, bound: 'lowerbound', shortname: 'pt', fullname: 'Peroneus tertius'},
{alpha: 0.7, muscleNum: 19, bound: 'lowerbound', shortname: 'pt', fullname: 'Peroneus tertius'},
{alpha: 0.8, muscleNum: 19, bound: 'lowerbound', shortname: 'pt', fullname: 'Peroneus tertius'},
{alpha: 0.9, muscleNum: 19, bound: 'lowerbound', shortname: 'pt', fullname: 'Peroneus tertius'},
{alpha: 0.5, muscleNum: 20, bound: 'lowerbound', shortname: 'pyr', fullname: 'Pyriformis'},
{alpha: 0.6, muscleNum: 20, bound: 'lowerbound', shortname: 'pyr', fullname: 'Pyriformis'},
{alpha: 0.7, muscleNum: 20, bound: 'lowerbound', shortname: 'pyr', fullname: 'Pyriformis'},
{alpha: 0.8, muscleNum: 20, bound: 'lowerbound', shortname: 'pyr', fullname: 'Pyriformis'},
{alpha: 0.9, muscleNum: 20, bound: 'lowerbound', shortname: 'pyr', fullname: 'Pyriformis'},
{alpha: 0.5, muscleNum: 21, bound: 'lowerbound', shortname: 'qf', fullname: 'Quadratus femoris'},
{alpha: 0.6, muscleNum: 21, bound: 'lowerbound', shortname: 'qf', fullname: 'Quadratus femoris'},
{alpha: 0.7, muscleNum: 21, bound: 'lowerbound', shortname: 'qf', fullname: 'Quadratus femoris'},
{alpha: 0.8, muscleNum: 21, bound: 'lowerbound', shortname: 'qf', fullname: 'Quadratus femoris'},
{alpha: 0.9, muscleNum: 21, bound: 'lowerbound', shortname: 'qf', fullname: 'Quadratus femoris'},
{alpha: 0.5, muscleNum: 22, bound: 'lowerbound', shortname: 'rf', fullname: 'Rectus femoris'},
{alpha: 0.6, muscleNum: 22, bound: 'lowerbound', shortname: 'rf', fullname: 'Rectus femoris'},
{alpha: 0.7, muscleNum: 22, bound: 'lowerbound', shortname: 'rf', fullname: 'Rectus femoris'},
{alpha: 0.8, muscleNum: 22, bound: 'lowerbound', shortname: 'rf', fullname: 'Rectus femoris'},
{alpha: 0.9, muscleNum: 22, bound: 'lowerbound', shortname: 'rf', fullname: 'Rectus femoris'},
{alpha: 0.5, muscleNum: 23, bound: 'lowerbound', shortname: 'sart', fullname: 'Sartorius'},
{alpha: 0.6, muscleNum: 23, bound: 'lowerbound', shortname: 'sart', fullname: 'Sartorius'},
{alpha: 0.7, muscleNum: 23, bound: 'lowerbound', shortname: 'sart', fullname: 'Sartorius'},
{alpha: 0.8, muscleNum: 23, bound: 'lowerbound', shortname: 'sart', fullname: 'Sartorius'},
{alpha: 0.9, muscleNum: 23, bound: 'lowerbound', shortname: 'sart', fullname: 'Sartorius'},
{alpha: 0.5, muscleNum: 24, bound: 'lowerbound', shortname: 'sm', fullname: 'Semimembranossus'},
{alpha: 0.6, muscleNum: 24, bound: 'lowerbound', shortname: 'sm', fullname: 'Semimembranossus'},
{alpha: 0.7, muscleNum: 24, bound: 'lowerbound', shortname: 'sm', fullname: 'Semimembranossus'},
{alpha: 0.8, muscleNum: 24, bound: 'lowerbound', shortname: 'sm', fullname: 'Semimembranossus'},
{alpha: 0.9, muscleNum: 24, bound: 'lowerbound', shortname: 'sm', fullname: 'Semimembranossus'},
{alpha: 0.5, muscleNum: 25, bound: 'lowerbound', shortname: 'sol', fullname: 'Soleus'},
{alpha: 0.6, muscleNum: 25, bound: 'lowerbound', shortname: 'sol', fullname: 'Soleus'},
{alpha: 0.7, muscleNum: 25, bound: 'lowerbound', shortname: 'sol', fullname: 'Soleus'},
{alpha: 0.8, muscleNum: 25, bound: 'lowerbound', shortname: 'sol', fullname: 'Soleus'},
{alpha: 0.9, muscleNum: 25, bound: 'lowerbound', shortname: 'sol', fullname: 'Soleus'},
{alpha: 0.5, muscleNum: 26, bound: 'lowerbound', shortname: 'st', fullname: 'Semitendinosus'},
{alpha: 0.6, muscleNum: 26, bound: 'lowerbound', shortname: 'st', fullname: 'Semitendinosus'},
{alpha: 0.7, muscleNum: 26, bound: 'lowerbound', shortname: 'st', fullname: 'Semitendinosus'},
{alpha: 0.8, muscleNum: 26, bound: 'lowerbound', shortname: 'st', fullname: 'Semitendinosus'},
{alpha: 0.9, muscleNum: 26, bound: 'lowerbound', shortname: 'st', fullname: 'Semitendinosus'},
{alpha: 0.5, muscleNum: 27, bound: 'lowerbound', shortname: 'ta', fullname: 'Tibialis anterior'},
{alpha: 0.6, muscleNum: 27, bound: 'lowerbound', shortname: 'ta', fullname: 'Tibialis anterior'},
{alpha: 0.7, muscleNum: 27, bound: 'lowerbound', shortname: 'ta', fullname: 'Tibialis anterior'},
{alpha: 0.8, muscleNum: 27, bound: 'lowerbound', shortname: 'ta', fullname: 'Tibialis anterior'},
{alpha: 0.9, muscleNum: 27, bound: 'lowerbound', shortname: 'ta', fullname: 'Tibialis anterior'},
{alpha: 0.5, muscleNum: 28, bound: 'lowerbound', shortname: 'tp', fullname: 'Tibialis posterior'},
{alpha: 0.6, muscleNum: 28, bound: 'lowerbound', shortname: 'tp', fullname: 'Tibialis posterior'},
{alpha: 0.7, muscleNum: 28, bound: 'lowerbound', shortname: 'tp', fullname: 'Tibialis posterior'},
{alpha: 0.8, muscleNum: 28, bound: 'lowerbound', shortname: 'tp', fullname: 'Tibialis posterior'},
{alpha: 0.9, muscleNum: 28, bound: 'lowerbound', shortname: 'tp', fullname: 'Tibialis posterior'},
{alpha: 0.5, muscleNum: 29, bound: 'lowerbound', shortname: 'vi', fullname: 'Vastus intermedius'},
{alpha: 0.6, muscleNum: 29, bound: 'lowerbound', shortname: 'vi', fullname: 'Vastus intermedius'},
{alpha: 0.7, muscleNum: 29, bound: 'lowerbound', shortname: 'vi', fullname: 'Vastus intermedius'},
{alpha: 0.8, muscleNum: 29, bound: 'lowerbound', shortname: 'vi', fullname: 'Vastus intermedius'},
{alpha: 0.9, muscleNum: 29, bound: 'lowerbound', shortname: 'vi', fullname: 'Vastus intermedius'},
{alpha: 0.5, muscleNum: 30, bound: 'lowerbound', shortname: 'vl', fullname: 'Vastus lateralis'},
{alpha: 0.6, muscleNum: 30, bound: 'lowerbound', shortname: 'vl', fullname: 'Vastus lateralis'},
{alpha: 0.7, muscleNum: 30, bound: 'lowerbound', shortname: 'vl', fullname: 'Vastus lateralis'},
{alpha: 0.8, muscleNum: 30, bound: 'lowerbound', shortname: 'vl', fullname: 'Vastus lateralis'},
{alpha: 0.9, muscleNum: 30, bound: 'lowerbound', shortname: 'vl', fullname: 'Vastus lateralis'},
{alpha: 0.5, muscleNum: 31, bound: 'lowerbound', shortname: 'vm', fullname: 'Vastus medialis'},
{alpha: 0.6, muscleNum: 31, bound: 'lowerbound', shortname: 'vm', fullname: 'Vastus medialis'},
{alpha: 0.7, muscleNum: 31, bound: 'lowerbound', shortname: 'vm', fullname: 'Vastus medialis'},
{alpha: 0.8, muscleNum: 31, bound: 'lowerbound', shortname: 'vm', fullname: 'Vastus medialis'},
{alpha: 0.9, muscleNum: 31, bound: 'lowerbound', shortname: 'vm', fullname: 'Vastus medialis'}
]
    },
  alphavals: function () {
    return ([{val:5},{val:6},{val:7},{val:8},{val:9}])
  },
  muscles: function () {
    return(
      [{shortname: 'adf'  , fullname: 'Adductor femoris', muscleNum: 1},
{shortname: 'adl'  , fullname: 'Adductor longus', muscleNum: 2},
{shortname: 'bfa'  , fullname: 'Biceps femoris anterior', muscleNum: 3},
{shortname: 'bfp'  , fullname: 'Biceps femoris posterior', muscleNum: 4},
{shortname: 'edl'  , fullname: 'Extensor digitorum longus', muscleNum: 5},
{shortname: 'fdl' , fullname: 'Flexor digitorum longus', muscleNum: 6},
{shortname: 'fhl'  , fullname: 'Flexor hallicus longus', muscleNum: 7},
{shortname: 'gmax' , fullname: 'Gluteus maximus', muscleNum: 8},
{shortname: 'gmed' , fullname: 'Gluteus medius', muscleNum: 9},
{shortname: 'gmin', fullname: 'Gluteus minimus', muscleNum: 10},
{shortname: 'grac' , fullname: 'Gracilis', muscleNum: 11},
{shortname: 'lg'   , fullname: 'Lateral gastrocnemius', muscleNum: 12},
{shortname: 'mg'   , fullname: 'Medial gastrocnemius', muscleNum: 13},
{shortname: 'pb'   , fullname: 'Peroneus brevis', muscleNum: 14},
{shortname: 'pec'  , fullname: 'Pectineus', muscleNum: 15},
{shortname: 'pl'   , fullname: 'Peroneus longus', muscleNum: 16},
{shortname: 'plan' , fullname: 'Plantaris', muscleNum: 17},
{shortname: 'psoas', fullname: 'Iliopsoas', muscleNum: 18},
{shortname: 'pt'   , fullname: 'Peroneus tertius', muscleNum: 19},
{shortname: 'pyr'  , fullname: 'Pyriformis', muscleNum: 20},
{shortname: 'qf'   , fullname: 'Quadratus femoris', muscleNum: 21},
{shortname: 'rf'   , fullname: 'Rectus femoris', muscleNum: 22},
{shortname: 'sart' , fullname: 'Sartorius', muscleNum: 23},
{shortname: 'sm'   , fullname: 'Semimembranossus', muscleNum: 24},
{shortname: 'sol'  , fullname: 'Soleus', muscleNum: 25},
{shortname: 'st'   , fullname: 'Semitendinosus', muscleNum: 26},
{shortname: 'ta'   , fullname: 'Tibialis anterior', muscleNum: 27},
{shortname: 'tp'   , fullname: 'Tibialis posterior', muscleNum: 28},
{shortname: 'vi'   , fullname: 'Vastus intermedius', muscleNum: 29},
{shortname: 'vl'   , fullname: 'Vastus lateralis', muscleNum: 30},
{shortname: 'vm', fullname: 'Vastus medialis', muscleNum: 31}
]
      )
  }

  })
}

if (Meteor.isServer) {
  Meteor.startup(function () {
    // code to run on server at startup
  });
}
